export const footerModel = [
  {
    title: "NEED HELP",
    content_one: "Chat with us",
    content_two: "Help Center",
    content_three: "Contact Us",
  },
  {
    title: "ABOUT JUMIA",
    content_one: "About us",
    content_two: "Jumia careers",
    content_three: "Jumia Express",
    content_four: "Terms and Conditions",
    content_five: "Privacy Notice",
    content_six: "Jumia Store Credit Terms & Conditions Notice",
    content_seven: "Jumia Payment information Guildlines",
    content_eight: "Cookies Notice",
    content_nine: "Jumia Global",
    content_ten: "Official Stores",
    content_eleven: "Flash Sales",
  },
  {
    title: "MAKE MONEY WITH JUMIA",
    content_one: "Sell on jumia",
    content_two: "Vendor hub",
    content_three: "Become a sale Consultant",
    content_four: "Our Blog",
  },
  {
    title: "JUMIA INTERNATIONAL",
    content_one: "Algeria",
    content_two: "Egypt",
    content_three: "Ghana",
    content_four: "Ivory Coast",
    content_five: "Kenya",
    content_six: "Morocco",
    content_seven: "Senegal",
    content_eight: "Uganda",
  },
  {
    title: "USEFUL LINKS",
    content_one: "Services Center",
    content_two: "How to shop on jusmia?",
    content_three: "Delivery options and timelines",
    content_four: "How to refund a product on jumia?",
    content_five: "Corporate and bulk purchase",
    content_six: "Report a Product",
    content_seven: "Dispute Resolution Policy",
    content_eight: "Returns & Refund Timelines",
    content_nine: "Return Policy",
    content_ten: "Pickup Stations",
  },
];